### ISSUE TITLE
All white  ! Can’t see the quoted posts and many things ! 

### ISSUE THREAD

**Issue by ShhubhamA** [bitclout/frontend#302]
![81DEAB0E-0A84-4C60-940F-26DA11940557](https://user-images.githubusercontent.com/71114510/126075343-fe50bf6d-2060-49f0-9259-f45059b9e0d9.png)

**Comment by teambrixmusic** [comment]
@JustifydWarrior any thoughts?

**Comment by iPaulPro** [comment]
![Screen_Shot_2021-07-18_at_1.01.53_PM.jpg](https://user-images.githubusercontent.com/354227/126076295-3f758af3-7880-484d-8174-6f1c0f1f0660.jpg)

Here's what it looks like on desktop. Looks this way no matter which theme is selected.

**Comment by teambrixmusic** [comment]
Posted that here. Thought it was a seperate glitch. Will close my issue.
https://github.com/bitclout/frontend/issues/301

**Comment by iPaulPro** [comment]
> Posted that here. Thought it was a seperate glitch. Will close my issue.
> https://github.com/bitclout/frontend/issues/301

Apologies, missed that. Yeah I assume these are both related to the theming change.

**Comment by teambrixmusic** [comment]
Probably a few things overlooked by @JustifydWarrior 
I synced the upstream and will look at it.
Stinks today was a super busy day for me with my kids so I'm on and off (Sunday)
Hopefully a few others can look too or Jus can get a moment.

**Comment by JustifydWarrior** [comment]
```
.modal-content {
...
background-color: var(--secalt); <// Looks like this line  failing on invalid variable:
```

if you remove it, it defaults to white.

it seems to be missing from the themes, where before there was a default. 

I believe the honest answer is that we need to add these to the themes, even if they refer to other vars

**Comment by JustifydWarrior** [comment]
actually no, that doesn't work... something else must be setting secalt to transparent

**Comment by JustifydWarrior** [comment]
okay... so it looks like the modal is outside the scope of the theme container, it needs access to the variables. they are all undefined for the modals. yes that's on me and my change for not testing the modals better. 

I should have a fix soon. but i'm honestly, wondering about the transparent defaults and where they come from.

**Comment by JustifydWarrior** [comment]
The only issue is the modal containers are added to the DOM outside the <app-root> tag. if you drag the modal inside, it works as expected. 

This is an small change but perhaps significant, and seems like the proper way to do it. But I have no clue on how to do it. 

I'll struggle around with it, but perhaps this is enough for someone faster to fix it.

**Comment by JustifydWarrior** [comment]
ok so it looks like the directive has been placed into all the modals already, but they're all missing the `[ngClass]="theme"`

**Comment by JustifydWarrior** [comment]
#307 should fix this

**Comment by harpreet9629** [comment]
> 
> 
> #307 should fix this

This makes issues in themes.

It changed Themes Colors, and Modal still show gray background and black text color. You have to fix that again.

https://github.com/bitclout/frontend/issues/305

**Comment by teambrixmusic** [comment]
Is it working now normally? Looks okay on my end? Can we close this?
